package ImgApp;

import java.io.Serializable;

/**
* ImgApp/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StoreImg.idl
* Wednesday, April 25, 2018 1:37:38 PM EET
*/

public final class Client implements org.omg.CORBA.portable.IDLEntity,Serializable
{
  public int Clientid = (int)0;
  public String name = null;
  public String email = null;
  public int password = (int)0;

  public Client ()
  {
  } // ctor
  public Client (int _Clientid, String _name, String _email, int _password)
  {
    Clientid = _Clientid;
    name = _name;
    email = _email;
    password = _password;
  } // ctor

} // class Client
