package ImgApp;

/**
* ImgApp/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StoreImg.idl
* Wednesday, April 25, 2018 1:37:38 PM EET
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ImgApp.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (ImgApp.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ImgApp.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ImgApp.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ImgApp.ClientHelper.type ();
  }

}
