package ImgApp;

/**
* ImgApp/ImgServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StoreImg.idl
* Wednesday, April 25, 2018 1:37:38 PM EET
*/

public final class ImgServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ImgApp.ImgServer value = null;

  public ImgServerHolder ()
  {
  }

  public ImgServerHolder (ImgApp.ImgServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ImgApp.ImgServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ImgApp.ImgServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ImgApp.ImgServerHelper.type ();
  }

}
