package ImgApp;


/**
* ImgApp/ImgServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StoreImg.idl
* Wednesday, April 25, 2018 1:37:38 PM EET
*/

public interface ImgServerOperations 
{
  void InputUser (String a, String b, int c);
  boolean GetClient (ImgApp.Client c1);
  byte[] Getimg (String ImgName);
} // interface ImgServerOperations
