package ImgApp;


/**
* ImgApp/ImgServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StoreImg.idl
* Wednesday, April 25, 2018 1:37:38 PM EET
*/

public interface ImgServer extends ImgServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ImgServer
